// flow-typed signature: a40d6211a12bfc5ad1b975c4d9a40191
// flow-typed version: <<STUB>>/react_v16.8.6/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react/cjs/react.development' {
  declare module.exports: any;
}

declare module 'react/cjs/react.production.min' {
  declare module.exports: any;
}

declare module 'react/umd/react.development' {
  declare module.exports: any;
}

declare module 'react/umd/react.production.min' {
  declare module.exports: any;
}

declare module 'react/umd/react.profiling.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react/cjs/react.development.js' {
  declare module.exports: $Exports<'react/cjs/react.development'>;
}
declare module 'react/cjs/react.production.min.js' {
  declare module.exports: $Exports<'react/cjs/react.production.min'>;
}
declare module 'react/index' {
  declare module.exports: $Exports<'react'>;
}
declare module 'react/index.js' {
  declare module.exports: $Exports<'react'>;
}
declare module 'react/umd/react.development.js' {
  declare module.exports: $Exports<'react/umd/react.development'>;
}
declare module 'react/umd/react.production.min.js' {
  declare module.exports: $Exports<'react/umd/react.production.min'>;
}
declare module 'react/umd/react.profiling.min.js' {
  declare module.exports: $Exports<'react/umd/react.profiling.min'>;
}
