// flow-typed signature: 2e8d96e578d88a507a9c9378d55b9c32
// flow-typed version: <<STUB>>/mongodb_v^3.3.0-beta2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongodb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongodb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongodb/lib/admin' {
  declare module.exports: any;
}

declare module 'mongodb/lib/aggregation_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/apm' {
  declare module.exports: any;
}

declare module 'mongodb/lib/async/async_iterator' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/common' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/ordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/bulk/unordered' {
  declare module.exports: any;
}

declare module 'mongodb/lib/change_stream' {
  declare module.exports: any;
}

declare module 'mongodb/lib/collection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/command_cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/constants' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/auth_provider' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/defaultAuthProviders' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/gssapi' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/mongo_credentials' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/mongocr' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/plain' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/scram' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/sspi' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/auth/x509' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/apm' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/command_result' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/commands' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/connect' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/connection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/logger' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/msg' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/pool' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/connection/utils' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/error' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/monitoring' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/server_description' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/server_selectors' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/server' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/srv_polling' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/topology_description' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sdam/topology' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/sessions' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/tools/smoke_plugin' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/mongos' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/read_preference' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/replset_state' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/replset' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/server' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/topologies/shared' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/transactions' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/uri_parser' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/utils' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/command' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/compression' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/constants' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/get_more' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/kill_cursors' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/query' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/shared' {
  declare module.exports: any;
}

declare module 'mongodb/lib/core/wireprotocol/write_command' {
  declare module.exports: any;
}

declare module 'mongodb/lib/cursor' {
  declare module.exports: any;
}

declare module 'mongodb/lib/db' {
  declare module.exports: any;
}

declare module 'mongodb/lib/dynamic_loaders' {
  declare module.exports: any;
}

declare module 'mongodb/lib/error' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/download' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs-stream/upload' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/chunk' {
  declare module.exports: any;
}

declare module 'mongodb/lib/gridfs/grid_store' {
  declare module.exports: any;
}

declare module 'mongodb/lib/mongo_client' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/add_user' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/admin_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/aggregate_operation' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/aggregate' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/bulk_write' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/close' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/collection_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/collections' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/command_v2' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/command' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/common_functions' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/connect' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/count_documents' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/count' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/create_collection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/create_index' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/create_indexes' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/cursor_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/db_ops' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/delete_many' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/delete_one' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/distinct' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/drop_index' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/drop_indexes' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/drop' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/estimated_document_count' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/execute_db_admin_command' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/execute_operation' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/explain' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/find_and_modify' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/find_one_and_delete' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/find_one_and_replace' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/find_one_and_update' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/find_one' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/geo_haystack_search' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/has_next' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/index_exists' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/index_information' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/indexes' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/insert_many' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/insert_one' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/is_capped' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/list_indexes' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/map_reduce' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/next' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/operation' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/options_operation' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/profiling_level' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/re_index' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/remove_user' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/rename' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/replace_one' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/set_profiling_level' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/stats' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/to_array' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/update_many' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/update_one' {
  declare module.exports: any;
}

declare module 'mongodb/lib/operations/validate_collection' {
  declare module.exports: any;
}

declare module 'mongodb/lib/read_concern' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/mongos' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/native_topology' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/replset' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/server' {
  declare module.exports: any;
}

declare module 'mongodb/lib/topologies/topology_base' {
  declare module.exports: any;
}

declare module 'mongodb/lib/url_parser' {
  declare module.exports: any;
}

declare module 'mongodb/lib/utils' {
  declare module.exports: any;
}

declare module 'mongodb/lib/write_concern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongodb/index' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/index.js' {
  declare module.exports: $Exports<'mongodb'>;
}
declare module 'mongodb/lib/admin.js' {
  declare module.exports: $Exports<'mongodb/lib/admin'>;
}
declare module 'mongodb/lib/aggregation_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/aggregation_cursor'>;
}
declare module 'mongodb/lib/apm.js' {
  declare module.exports: $Exports<'mongodb/lib/apm'>;
}
declare module 'mongodb/lib/async/async_iterator.js' {
  declare module.exports: $Exports<'mongodb/lib/async/async_iterator'>;
}
declare module 'mongodb/lib/bulk/common.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/common'>;
}
declare module 'mongodb/lib/bulk/ordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/ordered'>;
}
declare module 'mongodb/lib/bulk/unordered.js' {
  declare module.exports: $Exports<'mongodb/lib/bulk/unordered'>;
}
declare module 'mongodb/lib/change_stream.js' {
  declare module.exports: $Exports<'mongodb/lib/change_stream'>;
}
declare module 'mongodb/lib/collection.js' {
  declare module.exports: $Exports<'mongodb/lib/collection'>;
}
declare module 'mongodb/lib/command_cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/command_cursor'>;
}
declare module 'mongodb/lib/constants.js' {
  declare module.exports: $Exports<'mongodb/lib/constants'>;
}
declare module 'mongodb/lib/core/auth/auth_provider.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/auth_provider'>;
}
declare module 'mongodb/lib/core/auth/defaultAuthProviders.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/defaultAuthProviders'>;
}
declare module 'mongodb/lib/core/auth/gssapi.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/gssapi'>;
}
declare module 'mongodb/lib/core/auth/mongo_credentials.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/mongo_credentials'>;
}
declare module 'mongodb/lib/core/auth/mongocr.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/mongocr'>;
}
declare module 'mongodb/lib/core/auth/plain.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/plain'>;
}
declare module 'mongodb/lib/core/auth/scram.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/scram'>;
}
declare module 'mongodb/lib/core/auth/sspi.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/sspi'>;
}
declare module 'mongodb/lib/core/auth/x509.js' {
  declare module.exports: $Exports<'mongodb/lib/core/auth/x509'>;
}
declare module 'mongodb/lib/core/connection/apm.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/apm'>;
}
declare module 'mongodb/lib/core/connection/command_result.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/command_result'>;
}
declare module 'mongodb/lib/core/connection/commands.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/commands'>;
}
declare module 'mongodb/lib/core/connection/connect.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/connect'>;
}
declare module 'mongodb/lib/core/connection/connection.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/connection'>;
}
declare module 'mongodb/lib/core/connection/logger.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/logger'>;
}
declare module 'mongodb/lib/core/connection/msg.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/msg'>;
}
declare module 'mongodb/lib/core/connection/pool.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/pool'>;
}
declare module 'mongodb/lib/core/connection/utils.js' {
  declare module.exports: $Exports<'mongodb/lib/core/connection/utils'>;
}
declare module 'mongodb/lib/core/cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/core/cursor'>;
}
declare module 'mongodb/lib/core/error.js' {
  declare module.exports: $Exports<'mongodb/lib/core/error'>;
}
declare module 'mongodb/lib/core/index' {
  declare module.exports: $Exports<'mongodb/lib/core'>;
}
declare module 'mongodb/lib/core/index.js' {
  declare module.exports: $Exports<'mongodb/lib/core'>;
}
declare module 'mongodb/lib/core/sdam/monitoring.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/monitoring'>;
}
declare module 'mongodb/lib/core/sdam/server_description.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/server_description'>;
}
declare module 'mongodb/lib/core/sdam/server_selectors.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/server_selectors'>;
}
declare module 'mongodb/lib/core/sdam/server.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/server'>;
}
declare module 'mongodb/lib/core/sdam/srv_polling.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/srv_polling'>;
}
declare module 'mongodb/lib/core/sdam/topology_description.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/topology_description'>;
}
declare module 'mongodb/lib/core/sdam/topology.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sdam/topology'>;
}
declare module 'mongodb/lib/core/sessions.js' {
  declare module.exports: $Exports<'mongodb/lib/core/sessions'>;
}
declare module 'mongodb/lib/core/tools/smoke_plugin.js' {
  declare module.exports: $Exports<'mongodb/lib/core/tools/smoke_plugin'>;
}
declare module 'mongodb/lib/core/topologies/mongos.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/mongos'>;
}
declare module 'mongodb/lib/core/topologies/read_preference.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/read_preference'>;
}
declare module 'mongodb/lib/core/topologies/replset_state.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/replset_state'>;
}
declare module 'mongodb/lib/core/topologies/replset.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/replset'>;
}
declare module 'mongodb/lib/core/topologies/server.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/server'>;
}
declare module 'mongodb/lib/core/topologies/shared.js' {
  declare module.exports: $Exports<'mongodb/lib/core/topologies/shared'>;
}
declare module 'mongodb/lib/core/transactions.js' {
  declare module.exports: $Exports<'mongodb/lib/core/transactions'>;
}
declare module 'mongodb/lib/core/uri_parser.js' {
  declare module.exports: $Exports<'mongodb/lib/core/uri_parser'>;
}
declare module 'mongodb/lib/core/utils.js' {
  declare module.exports: $Exports<'mongodb/lib/core/utils'>;
}
declare module 'mongodb/lib/core/wireprotocol/command.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/command'>;
}
declare module 'mongodb/lib/core/wireprotocol/compression.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/compression'>;
}
declare module 'mongodb/lib/core/wireprotocol/constants.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/constants'>;
}
declare module 'mongodb/lib/core/wireprotocol/get_more.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/get_more'>;
}
declare module 'mongodb/lib/core/wireprotocol/index' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol'>;
}
declare module 'mongodb/lib/core/wireprotocol/index.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol'>;
}
declare module 'mongodb/lib/core/wireprotocol/kill_cursors.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/kill_cursors'>;
}
declare module 'mongodb/lib/core/wireprotocol/query.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/query'>;
}
declare module 'mongodb/lib/core/wireprotocol/shared.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/shared'>;
}
declare module 'mongodb/lib/core/wireprotocol/write_command.js' {
  declare module.exports: $Exports<'mongodb/lib/core/wireprotocol/write_command'>;
}
declare module 'mongodb/lib/cursor.js' {
  declare module.exports: $Exports<'mongodb/lib/cursor'>;
}
declare module 'mongodb/lib/db.js' {
  declare module.exports: $Exports<'mongodb/lib/db'>;
}
declare module 'mongodb/lib/dynamic_loaders.js' {
  declare module.exports: $Exports<'mongodb/lib/dynamic_loaders'>;
}
declare module 'mongodb/lib/error.js' {
  declare module.exports: $Exports<'mongodb/lib/error'>;
}
declare module 'mongodb/lib/gridfs-stream/download.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/download'>;
}
declare module 'mongodb/lib/gridfs-stream/index' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream'>;
}
declare module 'mongodb/lib/gridfs-stream/index.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream'>;
}
declare module 'mongodb/lib/gridfs-stream/upload.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs-stream/upload'>;
}
declare module 'mongodb/lib/gridfs/chunk.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/chunk'>;
}
declare module 'mongodb/lib/gridfs/grid_store.js' {
  declare module.exports: $Exports<'mongodb/lib/gridfs/grid_store'>;
}
declare module 'mongodb/lib/mongo_client.js' {
  declare module.exports: $Exports<'mongodb/lib/mongo_client'>;
}
declare module 'mongodb/lib/operations/add_user.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/add_user'>;
}
declare module 'mongodb/lib/operations/admin_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/admin_ops'>;
}
declare module 'mongodb/lib/operations/aggregate_operation.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/aggregate_operation'>;
}
declare module 'mongodb/lib/operations/aggregate.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/aggregate'>;
}
declare module 'mongodb/lib/operations/bulk_write.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/bulk_write'>;
}
declare module 'mongodb/lib/operations/close.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/close'>;
}
declare module 'mongodb/lib/operations/collection_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/collection_ops'>;
}
declare module 'mongodb/lib/operations/collections.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/collections'>;
}
declare module 'mongodb/lib/operations/command_v2.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/command_v2'>;
}
declare module 'mongodb/lib/operations/command.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/command'>;
}
declare module 'mongodb/lib/operations/common_functions.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/common_functions'>;
}
declare module 'mongodb/lib/operations/connect.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/connect'>;
}
declare module 'mongodb/lib/operations/count_documents.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/count_documents'>;
}
declare module 'mongodb/lib/operations/count.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/count'>;
}
declare module 'mongodb/lib/operations/create_collection.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/create_collection'>;
}
declare module 'mongodb/lib/operations/create_index.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/create_index'>;
}
declare module 'mongodb/lib/operations/create_indexes.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/create_indexes'>;
}
declare module 'mongodb/lib/operations/cursor_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/cursor_ops'>;
}
declare module 'mongodb/lib/operations/db_ops.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/db_ops'>;
}
declare module 'mongodb/lib/operations/delete_many.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/delete_many'>;
}
declare module 'mongodb/lib/operations/delete_one.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/delete_one'>;
}
declare module 'mongodb/lib/operations/distinct.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/distinct'>;
}
declare module 'mongodb/lib/operations/drop_index.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/drop_index'>;
}
declare module 'mongodb/lib/operations/drop_indexes.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/drop_indexes'>;
}
declare module 'mongodb/lib/operations/drop.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/drop'>;
}
declare module 'mongodb/lib/operations/estimated_document_count.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/estimated_document_count'>;
}
declare module 'mongodb/lib/operations/execute_db_admin_command.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/execute_db_admin_command'>;
}
declare module 'mongodb/lib/operations/execute_operation.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/execute_operation'>;
}
declare module 'mongodb/lib/operations/explain.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/explain'>;
}
declare module 'mongodb/lib/operations/find_and_modify.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/find_and_modify'>;
}
declare module 'mongodb/lib/operations/find_one_and_delete.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/find_one_and_delete'>;
}
declare module 'mongodb/lib/operations/find_one_and_replace.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/find_one_and_replace'>;
}
declare module 'mongodb/lib/operations/find_one_and_update.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/find_one_and_update'>;
}
declare module 'mongodb/lib/operations/find_one.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/find_one'>;
}
declare module 'mongodb/lib/operations/geo_haystack_search.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/geo_haystack_search'>;
}
declare module 'mongodb/lib/operations/has_next.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/has_next'>;
}
declare module 'mongodb/lib/operations/index_exists.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/index_exists'>;
}
declare module 'mongodb/lib/operations/index_information.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/index_information'>;
}
declare module 'mongodb/lib/operations/indexes.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/indexes'>;
}
declare module 'mongodb/lib/operations/insert_many.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/insert_many'>;
}
declare module 'mongodb/lib/operations/insert_one.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/insert_one'>;
}
declare module 'mongodb/lib/operations/is_capped.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/is_capped'>;
}
declare module 'mongodb/lib/operations/list_indexes.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/list_indexes'>;
}
declare module 'mongodb/lib/operations/map_reduce.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/map_reduce'>;
}
declare module 'mongodb/lib/operations/next.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/next'>;
}
declare module 'mongodb/lib/operations/operation.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/operation'>;
}
declare module 'mongodb/lib/operations/options_operation.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/options_operation'>;
}
declare module 'mongodb/lib/operations/profiling_level.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/profiling_level'>;
}
declare module 'mongodb/lib/operations/re_index.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/re_index'>;
}
declare module 'mongodb/lib/operations/remove_user.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/remove_user'>;
}
declare module 'mongodb/lib/operations/rename.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/rename'>;
}
declare module 'mongodb/lib/operations/replace_one.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/replace_one'>;
}
declare module 'mongodb/lib/operations/set_profiling_level.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/set_profiling_level'>;
}
declare module 'mongodb/lib/operations/stats.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/stats'>;
}
declare module 'mongodb/lib/operations/to_array.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/to_array'>;
}
declare module 'mongodb/lib/operations/update_many.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/update_many'>;
}
declare module 'mongodb/lib/operations/update_one.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/update_one'>;
}
declare module 'mongodb/lib/operations/validate_collection.js' {
  declare module.exports: $Exports<'mongodb/lib/operations/validate_collection'>;
}
declare module 'mongodb/lib/read_concern.js' {
  declare module.exports: $Exports<'mongodb/lib/read_concern'>;
}
declare module 'mongodb/lib/topologies/mongos.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/mongos'>;
}
declare module 'mongodb/lib/topologies/native_topology.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/native_topology'>;
}
declare module 'mongodb/lib/topologies/replset.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/replset'>;
}
declare module 'mongodb/lib/topologies/server.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/server'>;
}
declare module 'mongodb/lib/topologies/topology_base.js' {
  declare module.exports: $Exports<'mongodb/lib/topologies/topology_base'>;
}
declare module 'mongodb/lib/url_parser.js' {
  declare module.exports: $Exports<'mongodb/lib/url_parser'>;
}
declare module 'mongodb/lib/utils.js' {
  declare module.exports: $Exports<'mongodb/lib/utils'>;
}
declare module 'mongodb/lib/write_concern.js' {
  declare module.exports: $Exports<'mongodb/lib/write_concern'>;
}
